---

- name: install php
  homebrew: name=php71 state=latest install_options="--with-apache --with-gmp --without-fpm"

- name: install php modules
  homebrew: name={{item}} state=latest
  with_items:
    - php71-apcu
    - php71-imagick
    - php71-mcrypt
    - php71-intl
    - php71-opcache

- name: configure the php.ini settings
  lineinfile: >
    dest=/usr/local/etc/php/7.1/php.ini
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=yes
  with_items:
    - { regexp: 'max_execution_time', line: 'max_execution_time = 7200' }
    - { regexp: 'max_input_time', line: 'max_input_time = 7200' }
    - { regexp: 'memory_limit', line: 'memory_limit = -1' }
    - { regexp: 'post_max_size', line: 'post_max_size = 200M' }
    - { regexp: 'upload_max_filesize', line: 'upload_max_filesize = 200M' }
    - { regexp: 'max_file_uploads', line: 'max_file_uploads = 100' }
    - { regexp: 'date.timezone', line: 'date.timezone = Europe/Brussels' }
    - { regexp: 'date.default_latitude', line: 'date.default_latitude = 50.877369' }
    - { regexp: 'date.default_longitude', line: 'date.default_longitude = 4.684167' }
    - { regexp: 'session.cookie_httponly', line: 'session.cookie_httponly = 1' }
    - { regexp: ';?phar.readonly', line: 'phar.readonly = Off' }
